=== merchantwarrior/magento2/etc/merchant_warrior_payment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="payment">
        <xs:annotation>
            <xs:documentation>
                The root node for payment configuration
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="credit_cards" type="credit_cardsType" minOccurs="0" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="credit_cardsType">
        <xs:annotation>
            <xs:documentation>
                The containing node for a list of credit card types.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="type" type="MerchantWarriorTypeType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MerchantWarriorTypeType">
        <xs:annotation>
            <xs:documentation>
                The definition of a credit card type.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="label" type="xs:string" />
            <xs:element name="code_alt" type="xs:string" />
        </xs:all>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="order" type="xs:integer" use="required" />
    </xs:complexType>
</xs:schema>

=== merchantwarrior/magento2/etc/merchant_warrior_payment.xml
<?xml version="1.0"?>

<payment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:MerchantWarrior_Payment:etc/merchant_warrior_payment.xsd">
    <merchant_warrior_credit_cards>
        <type id="AE" order="0">
            <label>American Express</label>
            <code_alt>amex</code_alt>
        </type>
        <type id="VI" order="10">
            <label>Visa</label>
            <code_alt>visa</code_alt>
        </type>
        <type id="MC" order="20">
            <label>MasterCard</label>
            <code_alt>mc</code_alt>
        </type>
        <type id="DI" order="30">
            <label>Discover</label>
            <code_alt>discover</code_alt>
        </type>
        <type id="SM" order="40">
            <label>Maestro/Switch</label>
            <code_alt>maestro</code_alt>
        </type>
        <type id="JCB" order="50">
            <label>JCB</label>
            <code_alt>jcb</code_alt>
        </type>
        <type id="DN" order="60">
            <label>Diners</label>
            <code_alt>diners</code_alt>
        </type>
        <type id="UN" order="70">
            <label>UnionPay</label>
            <code_alt>cup</code_alt>
        </type>
    </merchant_warrior_credit_cards>
</payment>
